name: Aggregate Clash Subscriptions

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'sources.txt'

permissions:
  contents: write  # Give write permission to push changes

jobs:
  aggregate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pyyaml requests pytz
    
    - name: Run aggregator
      run: python aggregator.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add clash.yaml
        git diff --staged --quiet || (git commit -m "🔄 Auto-update clash.yaml" && git push)
