name: Build Subscription

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run aggregator script
      - name: Run aggregator
        run: node scripts/aggregate.js

      # 5. Commit changes (if any)
      - name: Commit subscription
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/subscription.yaml
          git commit -m "Update subscription" || echo "No changes to commit"

      # 6. Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-subscription
          base: main
          title: "Update subscription"
          body: "This PR updates the subscription.yaml file from aggregator workflow."
          commit-message: "Update subscription"
          delete-branch: false
